name: CMake Windows Release build

on: [push]

env:
  BUILD_TYPE: Release
  REPO_NAME: CMake-AtmelStudio7-compatibility
  GOOGLETEST_TAG: release-1.10.0
  CMAKE_CONFIGURATION: windows_vs2019_x64
  CMAKE_GENERATOR: "Visual Studio 15 2017"
  CMAKE_GENERATOR_PLATFORM: "x64"
  #CMAKE_GENERATOR_TOOLSET: "v142,version=14.27"


jobs:
  build:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      shell: powershell
      run: |
        git submodule init
        git submodule update

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Create Build Environment
      shell: powershell
      run: mkdir ${{runner.workspace}}/CMake-AtmelStudio7-compatibility/build

    - name: Configure CMake
      shell: powershell
      working-directory: ${{runner.workspace}}/CMake-AtmelStudio7-compatibility/build
      run: |
        cmake ../ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build CMake
      working-directory: ${{runner.workspace}}/CMake-AtmelStudio7-compatibility/build
      shell: powershell
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        dir
        cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Installing CMake
      working-directory: ${{runner.workspace}}/CMake-AtmelStudio7-compatibility/build
      shell: powershell
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        cmake --build . --config ${{env.BUILD_TYPE}} --target "install"
        dir
        dir install

    # Based on original Gitlab Cmake testing scripts
    - name: Run CTests
      working-directory: ${{runner.workspace}}/CMake-AtmelStudio7-compatibility/build
      shell: powershell
      run: ctest.exe --output-on-failure -V -S ../.github/ci/ctest_test.cmake -C ${{env.BUILD_TYPE}}

    - name: Run GTests
      working-directory: ${{runner.workspace}}/CMake-AtmelStudio7-compatibility
      shell: powershell
      run: python Tests/run_googletests.py build

    - name: Compress artifacts
      working-directory: ${{runner.workspace}}/CMake-AtmelStudio7-compatibility/build
      shell: powershell
      run: Compress-Archive -Path ./bin/${{env.BUILD_TYPE}}/*.exe -DestinationPath ./bin/${{env.BUILD_TYPE}}/CMakeAS7BuildArtifacts_winx64.zip

    # https://github.com/actions/upload-artifact
    - uses: actions/upload-artifact@v2
      with:
        name: CMakeAS7 build binaries (win x64)
        path: |
          ${{runner.workspace}}/CMake-AtmelStudio7-compatibility/build/bin/${{env.BUILD_TYPE}}/CMakeAS7BuildArtifacts_winx64.zip